In [5]:
import pandas as pd
df6_10 = pd.read_csv("DPE Research 6-10 Partner.csv", index_col=None)
df11_101 = pd.read_csv("DPE Research 11-101 Partner.csv", index_col=None)
df101_1000 = pd.read_csv("DPE Research 101-1000 Partner.csv", index_col=None)
df1000 = pd.read_csv("DPE Research 1000+Partner.csv", index_col=None)

In [7]:
partnerbase_df = pd.concat([df6_10, df11_101, df101_1000, df1000])

,Company,Industry,Founded,Number of Partners
0,[24]7.ai,Software,2000,10
1,AbbVie,Pharmaceutical,2013,6
2,ABC,"Social Media, Media Production",1946,9
3,Academy Sports Outdoors,Retail,1938,7
4,ACCOR HOTELS,"Publishing , Public Relations",1967,6
...,...,...,...,...
10,Red Hat,Software,1993,2508
11,Salesforce,Internet,1999,5207
12,SAP,Software,1972,1071
13,Symantec CloudSOC,"Software, Information Technology, Cyber Security",1982,1010
14,VMware,Software,1998,2262